service: product-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - sqs:SendMessage
      Resource:
        - "Fn::GetAtt": [Product, Arn]
        - "Fn::GetAtt": [Stock, Arn]
        - "Fn::GetAtt": [catalogItemsQueue, Arn] 

  environment:
    PRODUCT_TABLE:
      Ref: Product
    STOCK_TABLE:
      Ref: Stock

functions:  
  getProductsList:
    handler: functions/getProducts.handler
    events:
      - http:
          path: products
          method: get

  getProductsById:
    handler: functions/getProductById.handler
    events:
      - http:
          path: products/{productId}
          method: get

  createProduct:
    handler: functions/createProduct.handler
    events:
      - http:
          path: products
          method: post

  catalogBatchProcess:
    handler: functions/catalogBatchProcess.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt: [catalogItemsQueue, Arn] 
          batchSize: 5
          
resources:
  Resources:
    Product:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Product
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    Stock:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Stock
        AttributeDefinitions:
          - AttributeName: product_id
            AttributeType: S
        KeySchema:
          - AttributeName: product_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue  